service: tcgx-auth

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  httpApi:
    payload: '2.0'

  environment:
    NODE_ENV: ${sls:stage}
    STAGE: ${sls:stage}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:AdminInitiateAuth
          Resource: 
            - arn:aws:cognito-idp:us-east-1:${aws:accountId}:userpool/${env:ADMIN_USER_POOL_ID}

functions:
  tcgx-admin-post-confirmation:
    name: tcgx-admin-post-confirmation-${sls:stage}
    handler: lambdas/adminPostConfirmationHandler.handler
    environment:
      ADMIN_USER_POOL_ID: ${env:ADMIN_USER_POOL_ID}
      ADMIN_CLIENT_ID: ${env:ADMIN_CLIENT_ID}
      DEFAULT_USERNAME: ${env:DEFAULT_USERNAME}
      DEFAULT_PASSWORD: ${env:DEFAULT_PASSWORD}
      API_BASE_URL: ${env:API_BASE_URL}

custom:
  dotenv:
    path: .env.${opt:stage, 'dev'}
    logging: false

  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    target: node20
    platform: node
    concurrency: 10

package:
  individually: true 
