service: tcgx-auth

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  httpApi:
    payload: '2.0'

  environment:
    NODE_ENV: ${sls:stage}
    STAGE: ${sls:stage}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:AdminInitiateAuth
          Resource: 
            - arn:aws:cognito-idp:us-east-1:${aws:accountId}:userpool/${env:ADMIN_USER_POOL_ID}

functions:
  tcgx-admin-post-confirmation:
    name: tcgx-admin-post-confirmation-${sls:stage}
    handler: lambdas/adminPostConfirmationHandler.handler
    environment:
      ADMIN_USER_POOL_ID: ${env:ADMIN_USER_POOL_ID}
      ADMIN_CLIENT_ID: ${env:ADMIN_CLIENT_ID}
      ADMIN_DEFAULT_USERNAME: ${env:ADMIN_DEFAULT_USERNAME}
      ADMIN_DEFAULT_PASSWORD: ${env:ADMIN_DEFAULT_PASSWORD}
      API_BASE_URL: ${env:API_BASE_URL}
  tcgx-consumer-post-confirmation:
    name: tcgx-consumer-post-confirmation-${sls:stage}
    handler: lambdas/consumerPostConfirmationHandler.handler
    environment:
      CONSUMER_USER_POOL_ID: ${env:CONSUMER_USER_POOL_ID}
      CONSUMER_CLIENT_ID: ${env:CONSUMER_CLIENT_ID}
      CONSUMER_DEFAULT_USERNAME: ${env:CONSUMER_DEFAULT_USERNAME}
      CONSUMER_DEFAULT_PASSWORD: ${env:CONSUMER_DEFAULT_PASSWORD}
      API_BASE_URL: ${env:API_BASE_URL}

resources:
  Resources:
    AllowApiGatewayInvokeAdminPostConfirmation:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: !Sub arn:aws:lambda:us-east-1:${AWS::AccountId}:function:tcgx-admin-post-confirmation-${sls:stage}
        Action: lambda:InvokeFunction
        Principal: apigateway.amazonaws.com

custom:
  dotenv:
    path: .env.${opt:stage, 'dev'}
    logging: false

  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    target: node20
    platform: node
    concurrency: 10

package:
  individually: true 
